name: Publish to npm

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.16.0
          registry-url: 'https://registry.npmjs.org'

      - name: Setup npm
        run: npm install -g npm@10.8.1

      - name: Install dependencies
        run: npm install

      - name: Publish to npm
        run: npm login && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
