name: Sonar statistics

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Save sonar statistics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.14
      - name: Setup npm
        run: npm install -g npm@9.4.2
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: export NODE_OPTIONS=--max_old_space_size=8192 && npm run test
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
